fix(): backup works with default parameter

diff --git a/bin/backup b/bin/backup
--- a/bin/backup
+++ b/bin/backup
@@ -2,7 +2,7 @@
 
 set -e
 
-journal_dir=/media/jfriesen/Journal
+journal_dir=/media/jfriesen/Backup
 while getopts 'ph' opt; do
     case "$opt" in
     p)
@@ -11,21 +11,14 @@ while getopts 'ph' opt; do
         shift 2
       ;;
     h)
-        echo "Usage: $(basename $0) [-p] "
+        echo "Usage: $(basename $0) [-p /path/to/backup-media] "
+        exit 2
       ;;
     ?)
-      echo -e "Invalid command option.\nUsage $(basename $0) [-p] [-h]"
+    echo "Invalid command option.\nUsage $(basename $0) [-p /path/to/backup-media] [-h]"
+    exit 2
 esac
 done
-
-# TODO: Mount the $journal_dir if it does not exist
-
-exclusion_file=$HOME/.config/rsync/rsync-exclusion.txt
-
-if [ ! -f $exclusion_file ]; then
-    echo "Missing rsync exclusion file $exclusion_file" >&2
-    exit 2
-fi
 
 if [ ! -d $journal_dir ]; then
     echo "Missing $journal_dir directory" >&2
@@ -47,7 +40,8 @@ if command -v rsync > /dev/null; then
           --exclude=jfriesen/.rbenv \
           --exclude=*/tmp \
           --exclude=*/._tmp \
-          --exclude=*/*.tmp
+          --exclude=*/*.tmp \
+          --exclude=*/*.log \
     echo "Wrote backup to $journal_dir"
 else
     echo "Missing rsync command" >&2
